Начинает верстку index
htmlacademy-adaptive/1979299-sedona-25 pull request #2
Opened 2022-04-01 08:38 UTC by Shchipanov

2022-04-01 20:45 UTC, mkolotovich requested changes
Исправьте комментарии

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +  <body class="page__body">
Ошибка в БЭМ-нейминге. Нельзя использоват элемент без блока. У вас в коде не обяъявлен блок page. Для проверки БЭМ-нейминга используйте сервис - https://yoksel.github.io/html-tree/

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +        <div class="adventages__wrapper">
Опечатка в имени класса. У вас нет блок adventages в коде, зато есть advantages. Поэтому правильное имя элеента должно быть advantages__wrapper и я вам рекомендую пока отказаться от использования лишних обёрток

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +                    <p class="more__item__description souvenirs__description">Не только китайского, но и местного производства!</p>
У вас нет в коде блока more, зато есть блок more-list. Соответсвенно поэтому нельзя использовать элементы блока more и модификаторы элементов блока more. Также в БЭМ запрещено использовать элементы элементов, т.е. такой more__item__image элемент с точки зреня БЭМ не валидный

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +                    <img class="more__item__image bridge-image" src="img/main-images/bridge.jpg" width="320" height="260" alt="Мост Дьявола.">
Ну тут все тоже самое, что я и писал выше. Не объявлен блок more, а значит запрещено использовать элементы блока more и модификаторы элементов блока more.

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +        <div class="main-nav__wrapper">
Я бы вводил дополнительные обёртки по мере их необходимости. На данном этапе я считаю их избыточными.

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +      <div class="main-container__title title-site">
Если в блоке есть заголовок то лучше использовать семантеческие теги, например section

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +          <header class="stats__header">
Я считаю пока эти обёртки избыточными тегами, уберите их

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +              СЕДОНА — небольшой городок в АРИЗОНЕ,<br> заслущивающий большего!
тег br необходимо использовать только в случае, если не возможно сделать перенос как на макете. Здесь можно обойтись стилями

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +        <div class="order__wrapper">
Еще одна пока я считаю лишняя обёрточка

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +              <button class="search-link__button button"><span class="search-link__button__span">Найти Гостиницу</span></button>
нельзя вкладывать один интерактивный элемент внутрь другого

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +      <div class="main-footer__wrapper">
Пока лишний элемент. Вводите дополнительные обёртки по мере их необходимости, тогда вы точно будете знать нужны они вам или нет

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +        <div class="main-footer__hashtag hashtag">
Лишняя обертка для ссылки

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +        <div class="main-footer__social social">
Лишняя обертка

2022-04-01 20:45 UTC, mkolotovich commented on source/index.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">HTML Academy</a>
этого текста нет в макете. Внутри должно быть изображение. Можете использовать этот текст как описание к изображению

2022-04-02 06:24 UTC, Shchipanov commented on source/index.html
> +  <body class="page__body">
сделано

2022-04-02 06:33 UTC, Shchipanov commented on source/index.html
> +      <div class="main-container__title title-site">
сделано

2022-04-02 06:33 UTC, Shchipanov commented on source/index.html
> +        <div class="adventages__wrapper">
сделано

2022-04-02 07:00 UTC, Shchipanov commented on source/index.html
> +                    <p class="more__item__description souvenirs__description">Не только китайского, но и местного производства!</p>
изменил как понял

2022-04-02 07:01 UTC, Shchipanov commented on source/index.html
> +                    <img class="more__item__image bridge-image" src="img/main-images/bridge.jpg" width="320" height="260" alt="Мост Дьявола.">
исправлено как понято

2022-04-02 07:03 UTC, Shchipanov commented on source/index.html
> +        <div class="main-nav__wrapper">
блоки wrapper создавал как советовал Николай в лайве и так же в демке, для центрирования и поведения блока. Поэтому думаю оставить эти обертки

2022-04-02 07:04 UTC, Shchipanov commented on source/index.html
> +              <button class="search-link__button button"><span class="search-link__button__span">Найти Гостиницу</span></button>
исправил

2022-04-02 07:11 UTC, Shchipanov commented on source/index.html
> +      <div class="main-footer__wrapper">
писал выше почему его написал

2022-04-02 07:15 UTC, Shchipanov commented on source/index.html
> +        <div class="main-footer__hashtag hashtag">
ссделано

2022-04-04 06:13 UTC, mkolotovich requested changes

2022-04-04 06:13 UTC, mkolotovich commented on source/index.html
> +        <a class="main-foot__link" href="#">#visitSEDONA</a>
Ошибка в БЭМ нейминге. У вас нет блока main-foot в разметке, зато есть блок main-footer

2022-04-04 06:39 UTC, merged