Разметка внутренних страниц
htmlacademy-adaptive/1979299-sedona-25 pull request #3
Opened 2022-04-04 08:16 UTC by Shchipanov

---
:mortar_board: [Разметка внутренних страниц](https://up.htmlacademy.ru/adaptive/25/user/1979299/tasks/3)

:boom: https://htmlacademy-adaptive.github.io/1979299-sedona-25/3/

2022-04-05 06:49 UTC, mkolotovich requested changes
Добавьте на главную страницу ссылку на каталог. По заданию необходимо также разметить страницу формы.

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +        <img class="video__image" src="img/catalog-images/video.jpg" width="280" height="177" alt="Видео обзор.">
Ошибки в БЭМ нейминге. У вас не объявлени блок .video а значит соответственно не может быть его элементов

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +              <a class="site-list__link" href="#">
здесь должна быть ссылка на главную страницу

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +        <b class="thoto__overview">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</b>
здесь лучше разметить просто параграфом, в макете он не жирный

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +      <a class="main-header__logo">
В ТЗ [3.3.](https://up.htmlacademy.ru/adaptive/25/project/sedona#sedona-3-3) указано Логотип на внутренних страницах — это ссылка на главную страницу

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +              <span class="card__author">Автор фото: Борис</span>
здесь и далее лучше изменить тег на параграф, тогда порядок элементов будет как на макете

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +        <b class="video__overview">Смотрите видеопрезентацию и скорее за билетами, пока они не подорожали в очередной раз!</b>
измените тег на парагаф, в макете этот текст не жирный

2022-04-05 06:49 UTC, mkolotovich commented on source/catalog.html
> +          <b class="copyright__text">Разработано:</b>
этот текст в макете не жирный. Измените тег на спан

2022-04-05 09:17 UTC, Shchipanov commented on source/catalog.html
> +        <img class="video__image" src="img/catalog-images/video.jpg" width="280" height="177" alt="Видео обзор.">
исправил

2022-04-05 09:17 UTC, Shchipanov commented on source/catalog.html
> +              <a class="site-list__link" href="#">
сделано

2022-04-05 09:19 UTC, Shchipanov commented on source/catalog.html
> +        <b class="thoto__overview">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</b>
сделано

2022-04-05 09:27 UTC, Shchipanov commented on source/catalog.html
> +      <a class="main-header__logo">
сделано

2022-04-05 09:34 UTC, Shchipanov commented on source/catalog.html
> +              <span class="card__author">Автор фото: Борис</span>
сделано

2022-04-05 09:35 UTC, Shchipanov commented on source/catalog.html
> +        <b class="video__overview">Смотрите видеопрезентацию и скорее за билетами, пока они не подорожали в очередной раз!</b>
сделано

2022-04-05 09:36 UTC, Shchipanov commented on source/catalog.html
> +          <b class="copyright__text">Разработано:</b>
сделано

2022-04-07 07:00 UTC, mkolotovich requested changes
Исправьте комментарии

2022-04-07 08:47 UTC, Shchipanov commented on source/form.html
> +              <input class="contatcts-data__email" type="email" name="contacts-email" id="contacts-email" placeholder="Введите e-mail" required>
исправил

2022-04-07 08:51 UTC, Shchipanov commented on source/form.html
> +              <h3 class="yourself-data__title">Отчество:</h3>
сделано

2022-04-07 08:53 UTC, Shchipanov commented on source/form.html
> +              <h3 class="contacts-data__title">Электронная почта*:</h3>
сделано

2022-04-07 08:56 UTC, Shchipanov commented on source/form.html
> +                  <input class="visually-hidden difficult__input" type="radio" name="difficult" value="difficult">
сделано

2022-04-07 09:07 UTC, Shchipanov commented on source/form.html
> +              <input class="emotions-description__input" type="text" placeholder="Опишите подробно все свои восторги" required>
сделано

2022-04-07 09:18 UTC, mkolotovich requested changes

2022-04-07 09:18 UTC, mkolotovich commented on source/form.html
> +              <label for="yourself-patronymic">Отчество:<span class="visually-hidden">Добавьте отчество.</span>
здесь вам больше не нужны для доступности скрытые спаны, ведь у вас есть лейблы с текстом

2022-04-07 09:18 UTC, mkolotovich commented on source/form.html
> +              <label for="contacts-email">Электронная почта*:<span class="visually-hidden">Введите e-mail.</span>
Здесь тоже вам больше не нужны для доступности скрытые спаны, ведь у вас есть лейблы с текстом

2022-04-07 09:21 UTC, Shchipanov commented on source/form.html
> +              <label for="yourself-patronymic">Отчество:<span class="visually-hidden">Добавьте отчество.</span>
сделал

2022-04-07 09:55 UTC, mkolotovich requested changes
Исправьте комментарии с прошлой проверки

2022-04-07 10:52 UTC, merged