Делает файлы блоков импорт в файл stule.scss
htmlacademy-adaptive/1979299-sedona-25 pull request #4
Opened 2022-04-09 07:49 UTC by Shchipanov

2022-04-12 10:40 UTC, mkolotovich requested changes
В элементе 
```
<a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">Разработано:<svg class="copyright__link__image" aria-hidden="true" focusable="false" width="27" height="33">
 </a>
``` 
на главной странице в макете нет двоеточия после слова Разработано

2022-04-12 10:40 UTC, mkolotovich commented on source/sass/blocks/emotions.scss
> +
Создайте селектор .emotions-description__input::placeholder и задайте ему font-family: 'PT Sans';

2022-04-12 10:40 UTC, mkolotovich commented on source/sass/blocks/form.scss
> +  background: #81b3d2;
задайте font-family: 'PT Sans';

2022-04-12 10:40 UTC, mkolotovich commented on source/sass/blocks/form.scss
> +  color: rgba(51, 51, 51, 0.6);
задайте font-size: 12px;

2022-04-12 14:27 UTC, Shchipanov commented on source/sass/blocks/main-container.scss
> +  background-image: url("/img/main-images/fone-mobile.jpg");
сделано

2022-04-12 14:29 UTC, Shchipanov commented on source/sass/blocks/social.scss
> +    background-image: url("/img/footer-images/telegram.svg");
сделано

2022-04-12 14:30 UTC, Shchipanov commented on source/sass/blocks/social.scss
> +    background-image: url("/img/footer-images/youtube.svg");
сделано

2022-04-12 14:31 UTC, Shchipanov commented on source/sass/blocks/main-form.scss
> +  background-image: url("/img/main-images/fone-mobile.jpg");
сделано

2022-04-12 14:32 UTC, Shchipanov commented on source/form.html
> +        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">Разработано:<svg class="copyright__link__image" aria-hidden="true" focusable="false" width="27" height="33">
исправил

2022-04-12 14:51 UTC, Shchipanov commented on source/sass/blocks/form.scss
> +  background: #81b3d2;
сделано

2022-04-13 07:58 UTC, mkolotovich requested changes
Исправьте один комментарий и мердж)

2022-04-13 07:58 UTC, mkolotovich commented on source/form.html
> +              <textarea class="emotions-description__input" type="text" placeholder="Опишите подробно все свои восторги" required>Опишите подробно все свои восторги
у тега textarea нет атрибута type. Также удалите текст внутри тега  textarea. И закрывающий тег перенесите на одну строку с открывающим, иначе плейсхолдер не будет отображаться

2022-04-13 09:59 UTC, Shchipanov commented on source/form.html
> +              <textarea class="emotions-description__input" type="text" placeholder="Опишите подробно все свои восторги" required>Опишите подробно все свои восторги
все исправил

2022-04-13 13:43 UTC, merged