Начинает делать 5.7. Декоративные элементы главной страницы
htmlacademy-adaptive/1979299-sedona-25 pull request #7
Opened 2022-04-18 08:47 UTC by Shchipanov

2022-04-21 08:59 UTC, mkolotovich requested changes
Селектору .advantages__item__header p:last-child на десктопе задайте     width: 290px;  margin-left: auto; margin-right: auto;. Добавьте в разметку изображение треугольника после элемента <img class="title-site__image" src="img/header-images/main-title.svg" width="" height="" alt="Добро пожаловать в великолепную «Седону»." /">

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/food.scss
>    text-transform: uppercase;
на десктопе задайте     width: 303px;
    margin: auto;, а на планшете width: 157px;

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
создайте селектор .advantages__item:nth-child(1) .advantages__title и задайте ему на планшете width: 66%;
    margin: auto;

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
создайте селектор .advantages__item:nth-child(5) .advantages__title и задайте ему на планшете     width: 150px;
    margin: auto;

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
создайте селектор .advantages__item:nth-child(5) .advantages__item__header p и задайте ему на планшете     width: 234px;
    margin-left: auto;
    margin-right: auto;

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
создайте селектор .advantages__item:nth-child(7) .advantages__description и задайте ему на десктопе width: 277px;
    margin-left: auto;
    margin-right: auto;, а на планшете width: 148px;

2022-04-21 08:59 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
создайте селектор .advantages__item:nth-child(1) .advantages__description и задайте ему width: 282px;, на планшете     width: 190px;
    margin-left: auto;
    margin-right: auto;
}, а на десктопе  width: 290px;

2022-04-21 08:59 UTC, mkolotovich commented on source/index.html
> +      <nav class="main-nav main-nav--closed main-nav--opened main-nav--nojs">
уберите отсюда класс main-nav--nojs

2022-04-22 05:00 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
> +
сделано

2022-04-22 05:12 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
сделал немного по другому  создал селектор advantages__title-first

2022-04-22 05:17 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
сделал это до увиденного замечания  в селекторе .advantages__item__posts .advantages__title

2022-04-22 05:22 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
решил немного по другому до увиденного замечания падингами  в селекторе advantages__item__header-second

2022-04-22 05:24 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
также решил падингами селектора advantages__item__posts

2022-04-22 05:25 UTC, Shchipanov commented on source/sass/blocks/advantages.scss
извиняюсь и здесь сделал немного по другому но вроде все работает

2022-04-22 07:58 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с прошлой проверки. Селектору .page__body задайте     overflow: hidden;. Измените селектор @media (min-width: 768px) .souvenirs__description br на десктоп и задайте ему display inline

2022-04-22 09:09 UTC, merged